<?php
defined('ABSPATH') || exit;
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
class JSD_Debug
{

    public function __construct()
    {
        // Load Feature after Fields are Registered
        add_action('carbon_fields_fields_registered', [$this, 'load_debug_mode']);

    }

    public function load_debug_mode() {
        $debug = carbon_get_theme_option('jsd_debug_mode');

        if ($debug == true) {
            add_action('admin_menu', array($this, 'framework_settings_add_plugin_page'));
            add_action('admin_init', array($this, 'framework_settings_page_init'));
        }
    }

    public function framework_settings_add_plugin_page()
    {
        $plugin = JSD_Config::$info;
        add_menu_page(
            'Debug Mode', // page_title
            'Debug Mode', // menu_title
            'manage_options', // capability
            $plugin['slug'], // menu_slug
            array($this, 'create_example_package_page'), // function
            'dashicons-coffee', // icon_url
            99 // position
        );
    }

    public function create_example_package_page()
    {
        include(PLUGIN_DIR . 'views/settings.php');
    }

    /**
     * Take all HTML from file into one STRING
     * 
     * @param $filename Filename of Template in "views/" folder
     * @return $output String of the template Contents
     */

    public static function create_html($filename)
    {
        $file = PLUGIN_DIR . 'views/' . $filename . '.php';
        $output = file_get_contents($file);
        return $output;
    }

    public static function dump($var)
    {
        echo '<br>';
        echo '<pre>';
        var_dump($var);
        echo '</pre>';
        echo '<br>';
    }


}

new JSD_Debug;


